default: &default
  adapter:  <%= ENV['DB_ADAPTER'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_TEST_DATABASE'] %>

production:
  <<: *default
